export default {
    REQ_GET_TRANSACTION_DATA_ATTEMPT: 'REQ_GET_TRANSACTION_DATA_ATTEMPT',
    REQ_GET_TRANSACTION_DATA_SUCCESS: 'REQ_GET_TRANSACTION_DATA_SUCCESS',
    REQ_GET_TRANSACTION_DATA_FAILURE: 'REQ_GET_TRANSACTION_DATA_FAILURE',

    REQ_GET_TRANSACTION_LIST_ATTEMPT: 'REQ_GET_TRANSACTION_LIST_ATTEMPT',
    REQ_GET_TRANSACTION_LIST_SUCCESS: 'REQ_GET_TRANSACTION_LIST_SUCCESS',
    REQ_GET_TRANSACTION_LIST_FAILURE: 'REQ_GET_TRANSACTION_LIST_FAILURE',

    REQ_GET_SINGLE_TRANSACTION_ATTEMPT: 'REQ_GET_SINGLE_TRANSACTION_ATTEMPT',
    REQ_GET_SINGLE_TRANSACTION_SUCCESS: 'REQ_GET_SINGLE_TRANSACTION_SUCCESS',
    REQ_GET_SINGLE_TRANSACTION_FAILURE: 'REQ_GET_SINGLE_TRANSACTION_FAILURE',

    REQ_GET_PAYMENT_CONFIRMATION_ATTEMPT: 'REQ_GET_PAYMENT_CONFIRMATION_ATTEMPT',
    REQ_GET_PAYMENT_CONFIRMATION_SUCCESS: 'REQ_GET_PAYMENT_CONFIRMATION_SUCCESS',
    REQ_GET_PAYMENT_CONFIRMATION_FAILURE: 'REQ_GET_PAYMENT_CONFIRMATION_FAILURE',

    REQ_MAKE_PAYMENT_ATTEMPT: 'REQ_MAKE_PAYMENT_ATTEMPT',
    REQ_MAKE_PAYMENT_SUCCESS: 'REQ_MAKE_PAYMENT_SUCCESS',
    REQ_MAKE_PAYMENT_FAILURE: 'REQ_MAKE_PAYMENT_FAILURE',

    REQ_CREATE_REVIEW_ATTEMPT: 'REQ_CREATE_REVIEW_ATTEMPT',
    REQ_CREATE_REVIEW_SUCCESS: 'REQ_CREATE_REVIEW_SUCCESS',
    REQ_CREATE_REVIEW_FAILURE: 'REQ_CREATE_REVIEW_FAILURE',

    REQ_VENDOR_SELECT_TIME_ATTEMPT: 'REQ_VENDOR_SELECT_TIME_ATTEMPT',
    REQ_VENDOR_SELECT_TIME_SUCCESS: 'REQ_VENDOR_SELECT_TIME_ATTEMPT',
    REQ_VENDOR_SELECT_TIME_FAILURE: 'REQ_VENDOR_SELECT_TIME_FAILURE',

    REQ_SCAN_QR_CODE_ATTEMPT: 'REQ_SCAN_QR_CODE_ATTEMPT',
    REQ_SCAN_QR_CODE_SUCCESS: 'REQ_SCAN_QR_CODE_SUCCESS',
    REQ_SCAN_QR_CODE_FAILURE: 'REQ_SCAN_QR_CODE_FAILURE',

    REQ_REJECT_SERVICE_ATTEMPT: 'REQ_REJECT_SERVICE_ATTEMPT',
    REQ_REJECT_SERVICE_SUCCESS: 'REQ_REJECT_SERVICE_SUCCESS',
    REQ_REJECT_SERVICE_FAILURE: 'REQ_REJECT_SERVICE_FAILURE',

    REQ_CLEAR_ERROR: 'REQ_CLEAR_ERROR',
};
