export default {
    REQ_GET_TRANSACTION_DATA_ATTEMPT: 'REQ_GET_TRANSACTION_DATA_ATTEMPT',
    REQ_GET_TRANSACTION_DATA_SUCCESS: 'REQ_GET_TRANSACTION_DATA_SUCCESS',
    REQ_GET_TRANSACTION_DATA_FAILURE: 'REQ_GET_TRANSACTION_DATA_FAILURE',

    REQ_GET_TRANSACTION_LIST_ATTEMPT: 'REQ_GET_TRANSACTION_LIST_ATTEMPT',
    REQ_GET_TRANSACTION_LIST_SUCCESS: 'REQ_GET_TRANSACTION_LIST_SUCCESS',
    REQ_GET_TRANSACTION_LIST_FAILURE: 'REQ_GET_TRANSACTION_LIST_FAILURE',

    REQ_GET_PAYMENT_CONFIRMATION_ATTEMPT: 'REQ_GET_PAYMENT_CONFIRMATION_ATTEMPT',
    REQ_GET_PAYMENT_CONFIRMATION_SUCCESS: 'REQ_GET_PAYMENT_CONFIRMATION_SUCCESS',
    REQ_GET_PAYMENT_CONFIRMATION_FAILURE: 'REQ_GET_PAYMENT_CONFIRMATION_FAILURE',

    REQ_MAKE_PAYMENT_ATTEMPT: 'REQ_MAKE_PAYMENT_ATTEMPT',
    REQ_MAKE_PAYMENT_SUCCESS: 'REQ_MAKE_PAYMENT_SUCCESS',
    REQ_MAKE_PAYMENT_FAILURE: 'REQ_MAKE_PAYMENT_FAILURE',

    REQ_CREATE_REVIEW_ATTEMPT: 'REQ_CREATE_REVIEW_ATTEMPT',
    REQ_CREATE_REVIEW_SUCCESS: 'REQ_CREATE_REVIEW_SUCCESS',
    REQ_CREATE_REVIEW_FAILURE: 'REQ_CREATE_REVIEW_FAILURE',

    REQ_CLEAR_ERROR: 'REQ_CLEAR_ERROR',
};
