export default {
    REQ_GET_TRANSACTION_DATA_ATTEMPT: 'REQ_GET_TRANSACTION_DATA_ATTEMPT',
    REQ_GET_TRANSACTION_DATA_SUCCESS: 'REQ_GET_TRANSACTION_DATA_SUCCESS',
    REQ_GET_TRANSACTION_DATA_FAILURE: 'REQ_GET_TRANSACTION_DATA_FAILURE',

    REQ_GET_TRANSACTION_LIST_ATTEMPT: 'REQ_GET_TRANSACTION_LIST_ATTEMPT',
    REQ_GET_TRANSACTION_LIST_SUCCESS: 'REQ_GET_TRANSACTION_LIST_SUCCESS',
    REQ_GET_TRANSACTION_LIST_FAILURE: 'REQ_GET_TRANSACTION_LIST_FAILURE',
};
