# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

  pod 'Firebase/Messaging'

target 'Aladdin' do

  # Pods for Aladdin

  target 'AladdinTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
