# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Aladdin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Aladdin
  pod 'Firebase/Messaging'

  target 'AladdinTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
