export default {
  AUTH_SET_USER_TYPE: 'AUTH_SET_USER_TYPE',
  AUTH_LOGIN_USER: 'AUTH_LOGIN_USER',
  AUTH_USER_LOGIN_SUCCESS: 'AUTH_USER_LOGIN_SUCCESS',
  AUTH_USER_LOGIN_FAIL: 'AUTH_USER_LOGIN_FAIL',

  AUTH_CUSTOMER_SIGNUP_ATTEMPT: 'AUTH_CUSTOMER_SIGNUP_ATTEMPT',
  AUTH_CUSTOMER_SIGNUP_SUCCESS: 'AUTH_CUSTOMER_SIGNUP_SUCCESS',
  AUTH_CUSTOMER_SIGNUP_FAIL: 'AUTH_CUSTOMER_SIGNUP_FAIL',

  AUTH_RESET_PASSWORD: 'AUTH_RESET_PASSWORD',

  AUTH_VENDOR_SIGNUP_ATTEMPT: 'AUTH_VENDOR_SIGNUP_ATTEMPT',
  AUTH_VENDOR_SIGNUP_SUCCESS: 'AUTH_VENDOR_SIGNUP_SUCCESS',
  AUTH_VENDOR_SIGNUP_FAIL: 'AUTH_VENDOR_SIGNUP_FAIL',
};
