export default {
  AUTH_APP_START_UP: 'AUTH_APP_START_UP',

  AUTH_SET_USER_TYPE: 'AUTH_SET_USER_TYPE',
  AUTH_EMAIL_CHANGED: 'AUTH_EMAIL_CHANGED',
  AUTH_PASSWORD_CHANGED: 'AUTH_PASSWORD_CHANGED',
  AUTH_LOGIN_USER: 'AUTH_LOGIN_USER',
  AUTH_USER_LOGIN_SUCCESS: 'AUTH_USER_LOGIN_SUCCESS',
  AUTH_USER_LOGIN_FAIL: 'AUTH_USER_LOGIN_FAIL',

  AUTH_SIGN_UP_ATTEMPT: 'AUTH_SIGN_UP_ATTEMPT',
  AUTH_SIGN_UP_SUCCESS: 'AUTH_SIGN_UP_SUCCESS',
  AUTH_SIGN_UP_FAIL: 'AUTH_SIGN_UP_FAIL',

  AUTH_VENDOR_SET_DATA: 'AUTH_VENDOR_SET_DATA',
  AUTH_VENDOR_SET_CATEGORIES: 'AUTH_VENDOR_SET_CATEGORIES',

  AUTH_RESET_PASSWORD_ATTEMPT: 'AUTH_RESET_PASSWORD_ATTEMPT',
  AUTH_RESET_PASSWORD_SUCCESS: 'AUTH_RESET_PASSWORD_SUCCESS',
  AUTH_RESET_PASSWORD_FAIL: 'AUTH_RESET_PASSWORD_FAIL',

  AUTH_ADD_NEW_ADDRESS: 'AUTH_ADD_NEW_ADDRESS',

  AUTH_UPDATE_PROFILE: 'AUTH_UPDATE_PROFILE',

  AUTH_LOG_OUT: 'AUTH_LOG_OUT',
};
