export default {
  AUTH_SET_USER_TYPE: 'AUTH_SET_USER_TYPE',
  AUTH_EMAIL_CHANGED: 'AUTH_EMAIL_CHANGED',
  AUTH_PASSWORD_CHANGED: 'AUTH_PASSWORD_CHANGED',
  AUTH_LOGIN_USER: 'AUTH_LOGIN_USER',
  AUTH_USER_LOGIN_SUCCESS: 'AUTH_USER_LOGIN_SUCCESS',
  AUTH_USER_LOGIN_FAIL: 'AUTH_USER_LOGIN_FAIL',

  AUTH_SIGN_UP_ATTEMPT: 'AUTH_SIGN_UP_ATTEMPT',
  AUTH_SIGN_UP_SUCCESS: 'AUTH_SIGN_UP_SUCCESS',
  AUTH_SIGN_UP_FAIL: 'AUTH_SIGN_UP_FAIL',
  AUTH_VENDOR_SET_DATA: 'AUTH_VENDOR_SET_DATA',
  AUTH_VENDOR_SET_CATEGORIES: 'AUTH_VENDOR_SET_CATEGORIES',
  AUTH_VENDOR_SET_SUBCATEGORIES: 'AUTH_VENDOR_SET_SUBCATEGORIES',

  AUTH_RESET_PASSWORD_ATTEMPT: 'AUTH_RESET_PASSWORD_ATTEMPT',
  AUTH_RESET_PASSWORD_SUCCESS: 'AUTH_RESET_PASSWORD_SUCCESS',
  AUTH_RESET_PASSWORD_FAIL: 'AUTH_RESET_PASSWORD_FAIL',

  HOME_GET_ALL_SERVICES_ATTEMPT: 'HOME_GET_ALL_SERVICES_ATTEMPT',
  HOME_GET_ALL_SERVICES_SUCCESS: 'HOME_GET_ALL_SERVICES_SUCCESS',
  HOME_GET_ALL_SERVICES_FAIL: 'HOME_GET_ALL_SERVICES_FAIL',
};
