export default {
  SETTINGS_SET_SETTINGS: 'SETTINGS_SET_SETTINGS',

  SETTINGS_SET_PUSH_NOTIFICATIONS: 'SETTINGS_SET_PUSH_NOTIFICATIONS',

  SETTINGS_CHANGE_PASSWORD_ATTEMPT: 'SETTINGS_CHANGE_PASSWORD_ATTEMPT',
  SETTINGS_CHANGE_PASSWORD_SUCCESS: 'SETTINGS_CHANGE_PASSWORD_SUCCESS',
  SETTINGS_CHANGE_PASSWORD_FAILURE: 'SETTINGS_CHANGE_PASSWORD_FAILURE',
};
