export default {
  HOME_SET_SEARCH_CATEGORY: 'HOME_SET_SEARCH_CATEGORY',
  HOME_SET_SEARCH_SUBCATEGORY: 'HOME_SET_SEARCH_SUBCATEGORY',

  HOME_GET_VENDOR_LIST_ATTEMPT: 'HOME_GET_VENDOR_LIST_ATTEMPT',
  HOME_GET_VENDOR_LIST_SUCCESS: 'HOME_GET_VENDOR_LIST_SUCCESS',
  HOME_GET_VENDOR_LIST_FAILURE: 'HOME_GET_VENDOR_LIST_FAILURE', 

  HOME_GET_ALL_SERVICES_ATTEMPT: 'HOME_GET_ALL_SERVICES_ATTEMPT',
  HOME_GET_ALL_SERVICES_SUCCESS: 'HOME_GET_ALL_SERVICES_SUCCESS',
  HOME_GET_ALL_SERVICES_FAIL: 'HOME_GET_ALL_SERVICES_FAIL',
};
