export default {
  HOME_SET_SEARCH_CATEGORY: 'HOME_SET_SEARCH_CATEGORY',
  HOME_SET_SEARCH_SUBCATEGORY: 'HOME_SET_SEARCH_SUBCATEGORY',
  HOME_SET_SEARCH_ADDRESS: 'HOME_SET_SEARCH_ADDRESS',
  HOME_GET_COORDINATES: 'HOME_GET_COORDINATES',

  HOME_GET_VENDOR_LIST_ATTEMPT: 'HOME_GET_VENDOR_LIST_ATTEMPT',
  HOME_GET_VENDOR_LIST_SUCCESS: 'HOME_GET_VENDOR_LIST_SUCCESS',
  HOME_GET_VENDOR_LIST_FAILURE: 'HOME_GET_VENDOR_LIST_FAILURE',

  HOME_GET_ALL_SERVICES_ATTEMPT: 'HOME_GET_ALL_SERVICES_ATTEMPT',
  HOME_GET_ALL_SERVICES_SUCCESS: 'HOME_GET_ALL_SERVICES_SUCCESS',
  HOME_GET_ALL_SERVICES_FAILURE: 'HOME_GET_ALL_SERVICES_FAILURE',

  HOME_GET_VENDOR_DATA_ATTEMPT: 'HOME_GET_VENDOR_DATA_ATTEMPT',
  HOME_GET_VENDOR_DATA_SUCCESS: 'HOME_GET_VENDOR_DATA_SUCCESS',
  HOME_GET_VENDOR_DATA_FAILURE: 'HOME_GET_VENDOR_DATA_FAILURE',

  HOME_CREATE_OR_UPDATE_TRANSACTION_ATTEMPT: 'HOME_CREATE_OR_UPDATE_TRANSACTION_ATTEMPT',
  HOME_CREATE_OR_UPDATE_TRANSACTION_SUCCESS: 'HOME_CREATE_OR_UPDATE_TRANSACTION_SUCCESS',
  HOME_CREATE_OR_UPDATE_TRANSACTION_FAILURE: 'HOME_CREATE_OR_UPDATE_TRANSACTION_FAILURE',

};
