export default {
  HOME_SET_SEARCH_CATEGORY: 'HOME_SET_SEARCH_CATEGORY',
  HOME_SET_SEARCH_SUBCATEGORY: 'HOME_SET_SEARCH_SUBCATEGORY',
  
  HOME_GET_VENDOR_LIST_ATTEMPT: 'HOME_GET_VENDOR_LIST_ATTEMPT',
};
